# Generated by Django 3.1.5 on 2021-01-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
